### ISSUE TITLE
how to specify path in config file

### ISSUE THREAD

**Issue by chinnujacob** [notmatthancock/pylidc#25]
i am a beginner in LIDC dataset.could u please tell me how to specify path in config file.pylidcrc.I tried using the tutorial,but i got the following error.
 vol = scan.to_volume()
      2 print(vol.shape)
      3 
      4 print("%.2f, %.2f" % (vol.mean(), vol.std()))

~/anaconda3/lib/python3.6/site-packages/pylidc/Scan.py in to_volume(self, verbose)
    637         Return the scan as a 3D numpy array volume.
    638         """
--> 639         images = self.load_all_dicom_images(verbose=verbose)
    640 
    641         volume = np.zeros((512,512,len(images)))

~/anaconda3/lib/python3.6/site-packages/pylidc/Scan.py in load_all_dicom_images(self, verbose)
    286         if verbose: print("Loading dicom files ... This may take a moment.")
    287 
--> 288         path = self.get_path_to_dicom_files()
    289         fnames = [fname for fname in os.listdir(path)
    290                             if fname.endswith('.dcm')]

~/anaconda3/lib/python3.6/site-packages/pylidc/Scan.py in get_path_to_dicom_files(self)
    213                    "specified the `path` option in the configuration "
    214                    "file {}?")
--> 215             raise RuntimeError(msg.format(_get_config_file()))
    216 
    217         base = os.path.join(dicompath, self.patient_id)

RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file /home/user/.pylidcrc?

**Comment by notmatthancock** [comment]
.pylidcrc is plain text. Edit the path to point to the root folder of where the dicom data is stored on your particular machine.

**Comment by chinnujacob** [comment]
hii
this i s how i did  in .pylidcrc .stil  i get the same error.
[dicom]
path = /home/user/LIDC-IDRI
warn = True
can u suggest a solution

**Comment by notmatthancock** [comment]
The path that you have specified is not a real path. You have to update that to point to the root directory of where the LIDC data actually resides on your specific machine.

**Comment by chinnujacob** [comment]
hii
i have created a folder LIDC-IDRI in /home/user .and data s stored here.so isn't this the real path.what should i do now .please help

**Comment by chinnujacob** [comment]
hii
i have created a folder LIDC-IDRI in /home/user .and data s stored here.so isn't this the real path.what should i do now .please help

**Comment by notmatthancock** [comment]
Usually “user” should be your actual user account name. Are you on Linux? What’s the output of “ls /home/user/LIDC-IDRI”?

**Comment by chinnujacob** [comment]
hii
thank you so much.my problem is resolved.i got path correct

**Comment by notmatthancock** [comment]
ok...

**Comment by VidhiBishnoi** [comment]
Hello, Please help me out in the same issue above for the error:
RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file C:\Users\admin\pylidc.conf?
Iam using this code:
[dicom]
path = "C:/Users/admin/to/big_external_drive/datasets/LIDC-IDRI"
warn = True

**Comment by Jonas1312** [comment]
this `pylidc.conf` works for me:
```txt
[dicom]
path = D:\PhD Thesis\LIDC\LIDC-IDRI
```

try with backslash and remove quotes

**Comment by VidhiBishnoi** [comment]
Hello,
I have mentioned the path in my pylidc.conf file :
path = C:\Users\admin\pylidc.conf
But now new error comes after running
vol = scan.to_volume()
print(vol.shape)
i.e:

RuntimeError: Couldn't find DICOM files for
Scan(id=1,patient_id=LIDC-IDRI-0078) in
C:\Users\admin\pylidc.conf\LIDC-IDRI-0078

plz help to findout

**Comment by Jonas1312** [comment]
[dicom]
path = C:\Users\admin\to\big_external_drive\datasets\LIDC-IDRI

put that in your pylidc.conf

**Comment by VidhiBishnoi** [comment]
Thank you..
Now how to call this .conf file in the main file? As iam coding as given in
pylidc documentation. Starting my code with:
import pylidc as pl

# Query for all CT scans with desired traits.
scans = pl.query(pl.Scan).filter(pl.Scan.slice_thickness <= 1,
                                 pl.Scan.pixel_spacing <= 0.6)
print(scans.count())
# => 31

pid = 'LIDC-IDRI-0078'
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
till:
vol = scan.to_volume()
print(vol.shape)
but now the error is:

RuntimeError: Could not establish path to dicom files. Have you
specified the `path` option in the configuration file
C:\Users\admin\pylidc.conf?


Iam not able to find it? plz tell

**Comment by notmatthancock** [comment]
This error means that the `pylidc.conf`, but the path to the DICOM data that you've specified in that file does not exist. It would be helpful if you posted the contents of your `pylidc.conf` file.

**Comment by VidhiBishnoi** [comment]
[dicom]
path = C:\Users\admin\to\big_external_drive\datasets\LIDC-IDRI
warn = True
These r the contents in my pylidc.conf file. My dataset is downloaded in E:
drive. As this file will itself locate the dataset from the system i think.

**Comment by notmatthancock** [comment]
> path = C:\Users\admin\to\big_external_drive\datasets\LIDC-IDRI

This is a fake path. You need to replace this path with the actual path to the root folder of the LIDC data.

> As this file will itself locate the dataset from the system i think.

I'm sorry, I don't understand what you mean. This file needs to be updated by you to point to the data. pylidc does not scan your system to discover the root data location automatically, if that's what you're suggesting.

**Comment by VidhiBishnoi** [comment]
Thank you the issue is resolved.. Have you extracted the nodule? How to do
that?

**Comment by notmatthancock** [comment]
@VidhiBishnoi please read the guides here: https://pylidc.github.io/ If you still have questions about topics related to general usage (i.e., not related to this issue), then feel free to email me.

**Comment by VidhiBishnoi** [comment]
Thank you for helping..
Actually Iam trying to extract the nodule for other images today but got
stuck in a problem, hope you can help.
I followed the tutorial and achieved the same results for pid LIDC-Idri
0078 patient id. Now i changed the patient id to 0090 or other then iam
achieving the annotation image but after this when iam running the code
from :
ann = pl.query(pl.Annotation)\
        .filter(pl.Annotation.malignancy == 5).first()
Iam getting the results of 0078 id that was taken as an example in tutorial.

kindly help me in this regard. Also how can we extract the nodule for
complete dataset?


regards
Vidhi Bishnoi

**Comment by Jonas1312** [comment]
```python
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == "LIDC-IDRI-0090").first()
annotations = scan.annotations
ann = annotations[0]
mask_cropped = ann.boolean_mask()
bbox=ann.bbox()
mask = np.zeros(scan.to_volume().shape, dtype=np.bool)
mask[bbox] = mask_cropped
```

**Comment by VidhiBishnoi** [comment]
Hello , Yes i have done it already and i can see the output of applied scan
by the code:
scan.visualize(annotation_groups=nods)
After this i need to extract the nodule for which iam using the following
code:
import pylidc as pl
import matplotlib.pyplot as plt

#ann = pl.query(pl.Annotation).first()
vol = ann.scan.to_volume()

padding = [(30,10), (10,25), (0,0)]

mask = ann.boolean_mask(pad=padding)
bbox = ann.bbox(pad=padding)

fig,ax = plt.subplots(1,2,figsize=(5,3))

ax[0].imshow(vol[bbox][:,:,2], cmap=plt.cm.gray)
ax[0].axis('off')

ax[1].imshow(mask[:,:,2], cmap=plt.cm.gray)
ax[1].axis('off')

plt.tight_layout()
#plt.savefig("../images/mask_bbox.png", bbox_inches="tight")
plt.show()
after running this iam getting the same output as of 0078 i.e the example
taken in tutorial and also the output of 0078 is coming after running code:
ann.visualize_in_scan() to visualize annotations.
I dont knw how its happening even if i have given different patient id as
scan.
plz help

**Comment by Jonas1312** [comment]
Give us the full code script (and use triple backticks to improve readability!)

	```python
	insert code here
	```

**Comment by VidhiBishnoi** [comment]
Please find my python code below:
```
import pylidc as pl
import numpy as np
import matplotlib.pyplot as plt

# Query for all CT scans with desired traits.
scans = pl.query(pl.Scan).filter(pl.Scan.slice_thickness <= 1,
                                 pl.Scan.pixel_spacing <= 0.6)
print(scans.count())
# => 31

pid = 'LIDC-IDRI-0250'
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
nods = scan.cluster_annotations()

print("%s has %d nodules." % (scan, len(nods)))
for i,nod in enumerate(nods):
    print("Nodule %d has %d annotations." % (i+1, len(nods[i])))
vol = scan.to_volume()
scan.visualize(annotation_groups=nods)
annotations = scan.annotations
ann = annotations[0]
mask = ann.boolean_mask()
print(mask.shape, mask.dtype)
bbox = ann.bbox()
print(bbox)
vol = ann.scan.to_volume()
print(vol[bbox].shape)
import pylidc as pl
import matplotlib.pyplot as plt

#ann = pl.query(pl.Annotation).first()
vol = ann.scan.to_volume()

padding = [(30,10), (10,25), (0,0)]

mask = ann.boolean_mask(pad=padding)
bbox = ann.bbox(pad=padding)

fig,ax = plt.subplots(1,2,figsize=(5,3))

ax[0].imshow(vol[bbox][:,:,2], cmap=plt.cm.gray)
ax[0].axis('off')

ax[1].imshow(mask[:,:,2], cmap=plt.cm.gray)
ax[1].axis('off')

plt.tight_layout()
#plt.savefig("../images/mask_bbox.png", bbox_inches="tight")
plt.show()

ann.visualize_in_3d()
ann.visualize_in_scan()
```
The problem is as discussed previously.

**Comment by VidhiBishnoi** [comment]
Hello Sir, plz send me the solution of my problem.

**Comment by VidhiBishnoi** [comment]
kindly help me out..

**Comment by notmatthancock** [comment]
Hi @VidhiBishnoi like I mentioned already, a closed issue on an unrelated topic is not the avenue for this discussion.

If you are having a problem, then please open a separate issue that contains minimal steps to reproduce the issue you are experiencing, documenting the actual vs. expected results.

**Comment by VidhiBishnoi** [comment]
This issue iam getting while extracting nodule as I need to apply certain
machine learning techniques on the nodules extracted from this
dataset... that's why i asked..
Thank you

**Comment by Pollob001** [comment]
OSError: Couldn't find DICOM files for Scan(id=12,patient_id=LIDC-IDRI-0001).

pylidc.conf is:
[dicom]
path =C:\Users\Pollob\ct img\LIDC-IDRI
warn = True

actually where is the problem? anyone please help me
