### ISSUE TITLE
getting slow after loading a few dicoms

### ISSUE THREAD

**Issue by SunAnLan** [notmatthancock/pylidc#26]
I tried to extract 200 patient annotations and dicoms. However the pl.query gets very slow after a few loops

**Comment by notmatthancock** [comment]
I don’t know that I’d consider 200 to be “a few” :)

This is difficult to address without any steps to reproduce or minimal example code. Can you provide that?

**Comment by SunAnLan** [comment]
`for i, pid in enumerate(patients):
    if i > 200:
        break
    print("patient_num: {}".format(i))
    scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
    vol = scan.to_volume()
    malignancy = False
    m_score = 0
    patient_info = []
    # Cluster the annotations for the scan, and grab one.
    nods = scan.cluster_annotations()
    for nod in nods:
        if len(nod) >= 2:
            nod_info = {}
            # Perform a consensus consolidation and 50% agreement level.
            # We pad the slices to add context for viewing.
            cmask, cbbox, masks = consensus(nod, clevel=0.5, pad=[(2, 2), (2, 2), (2, 2)])
            vol_sample = vol[cbbox]
            for ann in nod:
                if type(ann.malignancy) == type(1):
                    m_score += ann.malignancy
                else:
                    m_score += m_list.index(ann.malignancy)
            m_score = m_score / len(nod)
            if m_score < 3:
                nod_num += 1
                nod_info['malignancy'] = False
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
            elif m_score > 3:
                nod_num += 1
                nod_info['malignancy'] = True
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
        if nod_num % 20 == 0:
            print("nod_num {}".format(nod_num))
    np.savez(pid + ".npz", data=patient_info)`

**Comment by SunAnLan** [comment]
for i, pid in enumerate(patients):
    if i > 200:
        break
    print("patient_num: {}".format(i))
    scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
    vol = scan.to_volume()
    malignancy = False
    m_score = 0
    patient_info = []
    # Cluster the annotations for the scan, and grab one.
    nods = scan.cluster_annotations()
    for nod in nods:
        if len(nod) >= 2:
            nod_info = {}
            # Perform a consensus consolidation and 50% agreement level.
            # We pad the slices to add context for viewing.
            cmask, cbbox, masks = consensus(nod, clevel=0.5, pad=[(2, 2), (2, 2), (2, 2)])
            vol_sample = vol[cbbox]
            for ann in nod:
                if type(ann.malignancy) == type(1):
                    m_score += ann.malignancy
                else:
                    m_score += m_list.index(ann.malignancy)
            m_score = m_score / len(nod)
            if m_score < 3:
                nod_num += 1
                nod_info['malignancy'] = False
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
            elif m_score > 3:
                nod_num += 1
                nod_info['malignancy'] = True
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
        if nod_num % 20 == 0:
            print("nod_num {}".format(nod_num))
    np.savez(pid + ".npz", data=patient_info)

**Comment by SunAnLan** [comment]
`for i, pid in enumerate(patients):
     if i > 200:
        break
    print("patient_num: {}".format(i))
    scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
    vol = scan.to_volume()
    malignancy = False
    m_score = 0
    patient_info = []
    # Cluster the annotations for the scan, and grab one.
    nods = scan.cluster_annotations()
    for nod in nods:
        if len(nod) >= 2:
            nod_info = {}
            # Perform a consensus consolidation and 50% agreement level.
            # We pad the slices to add context for viewing.
            cmask, cbbox, masks = consensus(nod, clevel=0.5, pad=[(2, 2), (2, 2), (2, 2)])
            vol_sample = vol[cbbox]
            for ann in nod:
                if type(ann.malignancy) == type(1):
                    m_score += ann.malignancy
                else:
                    m_score += m_list.index(ann.malignancy)
            m_score = m_score / len(nod)
            if m_score < 3:
                nod_num += 1
                nod_info['malignancy'] = False
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
            elif m_score > 3:
                nod_num += 1
                nod_info['malignancy'] = True
                nod_info['vol'] = vol_sample
                nod_info['mask'] = cmask
                patient_info.append(nod_info)
        if nod_num % 20 == 0:
            print("nod_num {}".format(nod_num))
    np.savez(pid + ".npz", data=patient_info)`

**Comment by SunAnLan** [comment]
for i, pid in enumerate(patients):
     if i > 200:
         break
    print("patient_num: {}".format(i))
    scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
    vol = scan.to_volume()
    malignancy = False
    m_score = 0
    patient_info = []
    # Cluster the annotations for the scan, and grab one.
    nods = scan.cluster_annotations()
    for nod in nods:
        if len(nod) >= 2:
            nod_info = {}
            # Perform a consensus consolidation and 50% agreement level.
            # We pad the slices to add context for viewing.
            cmask, cbbox, masks = consensus(nod, clevel=0.5, pad=[(2, 2), (2, 2), (2, 2)])
            # save process ...

**Comment by notmatthancock** [comment]
closing because stale
