### ISSUE TITLE
bbox(): Tuple meaning?

### ISSUE THREAD

**Issue by ganeshOnePlus** [notmatthancock/pylidc#27]
Hi, I print out this bounding box for first annotation as mentioned in tutorial. But I couldn't figure out the physical meaning of values in each of these tuple : slice(151, 185, None). Could you please help me understand it's meaning.
Thank you

import pylidc as pl

ann = pl.query(pl.Annotation).first()
print(ann.bbox())
# => (slice(151, 185, None), slice(349, 376, None), slice(44, 50, None))

**Comment by notmatthancock** [comment]
They're indices into CT scan volume when treated as a numpy volume. [See example usage here](https://pylidc.github.io/tuts/annotation.html#annotation-visualization).

To go from these indices to physical coordinates would require a bit more work and likely require information that is in the DICOM itself, but not stored in the pylidc database.

**Comment by ganeshOnePlus** [comment]
Thank you @notmatthancock for explaining but what is the last value 'None' in the tuple? Does it have some significance? I found out that None is the return value of functions that "don't return anything"

Also, I would like to know whether if we can query the LIDC dataset and get list of all the cases that has annotations describing coordinates and ground truth labels. For example like:
LIDC-IDRI-0066
LIDC-IDRI-0078
LIDC-IDRI-0095
LIDC-IDRI-0212
...
LIDC-IDRI-0888

**Comment by notmatthancock** [comment]
bbox returns a 3-tuple of slice instances, one for each of the 3 axes of the volume. It is the step parameter of the slice object that is None that you are observing. For example,

arr[1:5]

Is equivalent to

arr[slice(1, 5, None)]

Slice is a python built-in, so you can read more about it on the net.

Re: your second question, yes you can query for all scans or filter by patient ID. There examples in the docs.

**Comment by ganeshOnePlus** [comment]
Thank you so much for explanation. It made me more clear.

**Comment by L007** [comment]
so how can we obtain the physical bbox? (coordinate position)
