### ISSUE TITLE
Update database?

### ISSUE THREAD

**Issue by Jonas1312** [notmatthancock/pylidc#28]
Hi,

I'm working on the LIDC-IDRI dataset and your tool is really convenient, thanks a lot.

I wanted to know if the current `pylidc.sqlite` is up-to-date since the collection has been updated recently (2/24/2020)?

thanks

**Comment by notmatthancock** [comment]
Looking at [the site](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#dbf22419dbb1415080c3adfd39cdc651), it's not clear to me what exactly was updated. The red note says:

> *Replace any manifests downloaded prior to 2/24/2020. Please download a new manifest by clicking on the download button in the Images row of the table above. Manifests downloaded prior to 2/24/2020 may not include all series the collection.

I'm quite sure how to interpret this.

**Comment by Jonas1312** [comment]
Looks like it's just a maintenance update [https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#f633413761b746ff9e49dd8f0d5b679d](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI#f633413761b746ff9e49dd8f0d5b679d):

> *2/24/2020 Maintenance notes: Corrected table entries only (no additional data). Added SEG to Modalities (previously present but not listed). Corrected number of subjects from 1006 to 1010, corrected number of studies from 1296 to 1308, corrected number of series from 1296 to 1398, corrected number of images from 243,185 to 244,617, corrected image size from 124 to 125. The corrections are to the table information only.

So maybe updating the sqlite DB is not needed...
