### ISSUE TITLE
Access all DICOM attributes

### ISSUE THREAD

**Issue by Jonas1312** [notmatthancock/pylidc#30]
Hi,

Is there a way to access dicom attributes through pylidc?

Thanks

**Comment by notmatthancock** [comment]
Query-able attributes are limited to those defined on the respective classes. See the [`Scan` class API](https://pylidc.github.io/scan.html) and [example usage](https://pylidc.github.io/tuts/scan.html).

If you want to access the raw dicom data, then you can use the [`load_all_dicom_images()` member function on the `Scan` class](https://pylidc.github.io/scan.html#pylidc.Scan.load_all_dicom_images). This function returns a list of `pydicom.dataset.FileDataset` instances.

**Comment by Jonas1312** [comment]
ok thanks 👍
