### ISSUE TITLE
Problem when using Scan.visualize

### ISSUE THREAD

**Issue by HenriqueBBrum** [notmatthancock/pylidc#33]
Hello, when I try to use scan.visualize i keep getting this error:

Loading dicom files ... This may take a moment.
Traceback (most recent call last):
  File "pylidc_test.py", line 6, in <module>
    scan.visualize(annotation_groups=nodules)
  File "C:\Users\hbrum\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pylidc\Scan.py", line 542, in visualize
    for cell in scan_info_table.properties()['child_artists']:
KeyError: 'child_artists'

**Comment by notmatthancock** [comment]
This was recently fixed in https://github.com/notmatthancock/pylidc/pull/29 but I've not made a new release for pip in some time. I might do this soon. In the mean time, you can install the development version via

```bash
# remove old pylidc
pip uninstall pylidc
# clone the repo
git clone git@github.com:notmatthancock/pylidc.git
# install a dev copy
cd pylidc
pip install -e .
```

**Comment by HenriqueBBrum** [comment]
It worked, thanks!!

**Comment by notmatthancock** [comment]
@HenriqueBBrum FYI I just uploaded a new version that includes the fix to pypi
