### ISSUE TITLE
bbox(): cut and save annotations

### ISSUE THREAD

**Issue by anatielsantos** [notmatthancock/pylidc#37]
Hi!
Your library is amazing!

How can i cut the annotations from the base and save it as a new image (just the annotations) using pylidc? Is it possible?

**Comment by notmatthancock** [comment]
I'm not sure what you're referring to by "base" in this context. It sounds like you want something along the lines of this example: https://pylidc.github.io/tuts/consensus.html ?

For example,

```python
import numpy as np
import matplotlib.pyplot as plt

import pylidc as pl
from pylidc.utils import consensus


# Query for a scan, and convert it to an array volume.
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == 'LIDC-IDRI-0001').first()
vol = scan.to_volume()

nodules = scan.cluster_annotations()
annotations = nodules[0]
consensus_mask, consensus_bbox, _ = consensus(
    annotations,
    clevel=0.5,
    pad=[(20,20), (20,20), (0,0)]
)

k = consensus_mask.shape[-1] // 2

plt.subplot(121)
plt.imshow(vol[consensus_bbox][:, :, k], cmap='gray')
plt.subplot(122)
plt.imshow(consensus_mask[:, :, k], cmap='gray')
plt.show()
```

Outputs:

![image](https://user-images.githubusercontent.com/1588456/83933498-a4b83c00-a76e-11ea-9c2d-a7b0b0f83b75.png)

**Comment by anatielsantos** [comment]
I wasn't very clear. I mean, to save each annotations from dataset LIDC as a new image. To save just the annotation region. Thanks!

**Comment by notmatthancock** [comment]
So, is what I posted above what you're looking for or...?

**Comment by anatielsantos** [comment]
I'll try it. I guess it will works. If don't work I post here, if work I'll post too. Thanks one more time.

**Comment by notmatthancock** [comment]
OK. Feel free to close this issue if you find the above examples work for you.

**Comment by anatielsantos** [comment]
Hi, your post was useful. Can help me in more one thing? Is possible save just nodules of GGO and consolidation, for exemple?

**Comment by notmatthancock** [comment]
Yes, but keep in mind that it depends on what you mean by a GGO nodule, since attributes like GGO are assigned individually by the annotators. So, do you mean nodules where at least 1 annotator assigned GGO as the texture attribute? At least 50% of annotators?

In any case, I would start by looping through each `Scan`, and cluster the annotations using `Scan.cluster_annotations` in order to group annotations belonging to the same physical nodule. So, something like:

```python
for scan in pl.query(pl.Scan):
    # annotation_groups is a list of of lists of Annotation's
    annotation_groups = scan.cluster_annotations()
```

Next, for each annotation group, implement your criteria of what qualifies as GGO. E.g.,

```python
for nodule_annotations in annotation_group:
    # Only consider nodules with 4 annotators and have >= 50% indicating GGO
    if (len(nodule_annotations) == 4 and
            sum([a.texture == 1 for a in nodule_annotations]) >= 2):
        # Do whatever you want, e.g.,
        # consensus(nodule_annotations)
```

**Comment by anatielsantos** [comment]
Thanks! It works.

**Comment by anatielsantos** [comment]
Man, I have another issue. I got do this for 2D nodules images. How can I do the same for 3D volume of interest? Thanks!

**Comment by notmatthancock** [comment]
>  How can I do the same for 3D volume of interest?

The image and consensus masks are volumes.

**Comment by anatielsantos** [comment]
Ok. I do this:

`for scan in pl.query(pl.Scan):
        # annotation_groups is a list of of lists of Annotation's
        annotation_groups = scan.cluster_annotations()
        vol = scan.to_volume()

        # Next, for each annotation group, implement your criteria of what qualifies as GGO. E.g.,
        for nodule_annotations in annotation_groups:
            # Only consider nodules with 4 annotators and have >= 50% indicating GGO
            if (len(nodule_annotations) >= 2 and sum([a.texture == 1 for a in nodule_annotations]) >= 1):
                consensus_mask, consensus_bbox, _ = consensus(
                    nodule_annotations,
                    clevel=0.5,
                    pad=[(5,5), (5,5), (0,0)]
                )

                image = np.asarray(vol[consensus_bbox][:, :, :]).transpose(2,0,1)
                mask_image = np.float32(np.array(consensus_mask[:, :, :])).transpose(2,0,1)`

Thaks!
