### ISSUE TITLE
Can I obtain annotated non-nodules from using pylidc?

### ISSUE THREAD

**Issue by shakjm** [notmatthancock/pylidc#39]
Hi,

I would like to know if there's any part of the codes I can change to concentrate on annotated non-nodules by the radiologist on the LIDC dataset? The idea is to preprocess these non-nodules as crops alongside with the nodules. Would appreciate if I could get some help on this.

**Comment by notmatthancock** [comment]
No, not with pylidc. The underlying sqlite database is populated only with nodule annotations. You are of course free to peruse the script used to create the backing sqlite database, and modify it to parse and include non-nodule annotations, but this would be a separate endeavor from pylidc. Here's the relevant lines in the DB population script: https://github.com/notmatthancock/pylidc/blob/20beb61b8def1b417813a5b41155a55a8f0f7f5d/_populate_db/populate.py#L125-L126

**Comment by shakjm** [comment]
> No, not with pylidc. The underlying sqlite database is populated only with nodule annotations. You are of course free to peruse the script used to create the backing sqlite database, and modify it to parse and include non-nodule annotations, but this would be a separate endeavor from pylidc. Here's the relevant lines in the DB population script:
> 
> https://github.com/notmatthancock/pylidc/blob/20beb61b8def1b417813a5b41155a55a8f0f7f5d/_populate_db/populate.py#L125-L126

Hello,

Thank you so much for the information. Have looked into the codes myself, and find it a bit too complex for myself to dive into this. I do understand that I have to change the unblindedReadNodule to nonNodule reading sessions. 

Thank you again for the help! Take care!
