### ISSUE TITLE
How to access NBIA via pylidc

### ISSUE THREAD

**Issue by dinhanhx** [notmatthancock/pylidc#44]
This question might be stupid. is it possible to access NBIA? If then how can I do it?

https://www.cancerimagingarchive.net/nbia-search/?CollectionCriteria=LIDC-IDRI

**Comment by notmatthancock** [comment]
Are you asking if pylidc provides an API for interacting with the NBIA database? If so, then no.

You might want to look into using [NBIA's REST API](https://wiki.cancerimagingarchive.net/display/Public/NBIA+Search+REST+API+Guide) using python `requests` or something instead.
