### ISSUE TITLE
how to obtain the physical bbox?

### ISSUE THREAD

**Issue by L007** [notmatthancock/pylidc#46]
how can we obtain the physical bbox? (coordinate position) @notmatthancock 
Is there a tutorial that can be a reference for me?

thanks

**Comment by Jonas1312** [comment]
```python
consensus_mask, consensus_bbox, masks = consensus(nodule_anns, clevel=0.5)
bin_mask = np.zeros(sitk_ct_scan.GetSize(), dtype=np.int32)
bin_mask[consensus_bbox] = consensus_mask.astype(np.int32)

# convert to sitk
bin_mask = np.transpose(bin_mask, axes=(2, 0, 1))  # channel first
sitk_mask = sitk.GetImageFromArray(bin_mask)  # numpy to sitk
sitk_mask.CopyInformation(sitk_ct_scan)
sitk_mask = sitk.Cast(sitk_mask, sitk.sitkInt32) 
```

**Comment by notmatthancock** [comment]
The example above shows how to get bounding box coordinates from a consensus of annotations. [Here's an example](https://pylidc.github.io/tuts/annotation.html#annotation-visualization) that shows how to get the bounding box data for a single annotation.

Either way, the returned bounding boxes are index slices into the image volume. If by physical coordinates, you mean that you want to know the position in physical space with reference to some origin, then you'll have to use [slice spacing](https://pylidc.github.io/scan.html#pylidc.Scan.slice_spacing), [pixel spacing](https://pylidc.github.io/scan.html#pylidc.Scan.pixel_spacing), and likely some additional attributes in the DICOM files themselves.

**Comment by L007** [comment]
hai @notmatthancock  I mean, how to get a bounding box in the form of 4 coordinate points x1, x2, y1, y2
if I check the xml in the lidc folder the coordinates are points for masking

is there any suggestion to make a bounding box to mark the ROI from 4 coordinate points?

and how to get the 4 coordinate points of the ROI?

thanks

**Comment by Jonas1312** [comment]
could you make the effort to read the documentation (if it is not too much to ask)? https://pylidc.github.io/annotation.html#pylidc.Annotation.bbox
