### ISSUE TITLE
Where to find pylidc.conf file in Google Colab?

### ISSUE THREAD

**Issue by youssef12347** [notmatthancock/pylidc#47]
The root folder is not accessible in colab, so how do I access the configuration file to edit it? Should I create the file? 

Keep receiving the same error: "RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file /root/.pylidcrc?"

**Comment by notmatthancock** [comment]
Functions that use image data from DICOM files will raise this error. DICOM data is required to be present on the local file system for those functions, and the pylidcrc file is used to configure the location of the DICOM files. I would not expect this portion of pylidc to work on a google colab notebook.
