### ISSUE TITLE
Not able to do path configuration for pylidc on mac

### ISSUE THREAD

**Issue by Snigda0402** [notmatthancock/pylidc#48]
RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file /Users/gedelasnigda/.pylidcrc?
 I am getting this runtime error

I have put this code in my configuration file:
[dicom] 
path=/Users/snigda/Desktop/x/LIDC-IDRI  
warn = True

**Comment by notmatthancock** [comment]
The error message shows a different username than the one listed in your config. Are you sure you have the `.pylidcrc` config file in the correct user directory?
