### ISSUE TITLE
RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file C:\Users\user\pylidc.conf?

### ISSUE THREAD

**Issue by Dhruv-Singhh** [notmatthancock/pylidc#49]
i have specified the correct path of my dicom files but still i am getting this error. i hope you could help me in this.
i specified the path like this.
![image](https://user-images.githubusercontent.com/73129686/121367456-f4b87880-c957-11eb-8111-bc94c8ce87a0.png)

![image](https://user-images.githubusercontent.com/73129686/121367591-0dc12980-c958-11eb-844b-54b15756a289.png)

error is this
![image](https://user-images.githubusercontent.com/73129686/121367742-30534280-c958-11eb-969d-56d6073f5ff9.png)

**Comment by notmatthancock** [comment]
I don't have enough information from your screenshots. The error message shows that the config file is missing at [the expected pylidc location](https://pylidc.github.io/install.html). Did you check if the file exists?
