### ISSUE TITLE
Pylidc Annotation Class

### ISSUE THREAD

**Issue by jasonjin1** [notmatthancock/pylidc#52]
Sorry if this is a dumb question but I'm just getting started with Pylidc and I'm having trouble using the Annotation class to get the masks of different LIDC scans. 
The code says 
ann = pl.query(pl.Annotation).first()
but as far as I can tell, this only gets the scan for the LIDC-0078 data. How would I modify this to run the scan for other LIDC data? Using .filter(Patient ID) does not work either. Thank you

**Comment by notmatthancock** [comment]
The patient ID attribute is stored on the Scan model, so you have to query on that or do a join. Check out the Scan tutorial here: https://pylidc.github.io/tuts/scan.html

**Comment by jasonjin1** [comment]
Hi, I have tried that but still can't seem to change the patient ID for the annotation. Do you think you could provide an example code to get the annotation for a different ID than 0078? When I try to scan it and then use the annotation class, ann = pl.query(pl.Annotation).first() it still only gets 0078. Thank you in advance.

**Comment by notmatthancock** [comment]
You can query annotations directly, but the relationship from scan to annotation is 1-to-many. So, you can query for the scan first having the patient ID you desire. Then, access the annotations for that scan, e.g.,
```python
import pylidc as pl

# whatever patient id you want
patient_id = "LIDC-IDRI-0001"

scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == patient_id).first()
print(scan.annotations)
# [Annotation(id=84,scan_id=12), Annotation(id=85,scan_id=12), Annotation(id=86,scan_id=12), Annotation(id=87,scan_id=12)]

ann = scan.annotations[0]
print(scan.patient_id, ann.scan == scan)
# LIDC-IDRI-0001, True
```
