### ISSUE TITLE
3D Annotation

### ISSUE THREAD

**Issue by HarryChenn** [notmatthancock/pylidc#53]
Hi, I'm so sorry to bother you. I have tried to visualize the mask and slices through the ann.visualize_in_3d(), but the output is just a three-dimensional image shown in my text editor. Therefore, I am wondering if there are actual 3d data in the LIDC datasets that I can interact with in different formats. Furthermore, is there a way that I can extract and save the 3d visualization on my computer just like what I can do for the slice and mask images?

**Comment by HarryChenn** [comment]
![4341656478135_ pic](https://user-images.githubusercontent.com/39673647/176354009-97657133-6324-49d4-a024-b6b5b6423808.jpg)
![4351656478267_ pic](https://user-images.githubusercontent.com/39673647/176354255-8f1b6828-68a0-40b7-93a7-af636b96ab46.jpg)

I'm sorry for not phrasing my question well. I have attached the code I am using above and you can see that the preview on the right is what I am getting from the mask and slice. So my question is that I can save the mask and slice by using fig.savefig, so I am wondering if there is any way to save the 3d images?

**Comment by notmatthancock** [comment]
> so I am wondering if there is any way to save the 3d images?

By image you mean the 3d matplotlib rendering of the annotation? or the CT image volume?

**Comment by HarryChenn** [comment]
I will need the CT image volume, but if there is any way to also get the 3d matplotlib rendering of the annotation, it will be even helpful!
Thank you!

**Comment by notmatthancock** [comment]
The CT image volume is returned by `to_volume`. You have this in your code at line 10 in your screenshot. The 3d matplotlib rendering can be saved with `plt.savefig` after calling `visualize_in_3d()`.

**Comment by HarryChenn** [comment]
Thank you so much for helping me! I have tried to use `plt.savefig` after `visualize_in_3d()`, but it ends up getting me blank images. I think this is a dumb question, but I think I am lacking some codes before saving the images.

Here is the code:
![4371656658241_ pic](https://user-images.githubusercontent.com/39673647/176840281-9122edd3-af47-4f37-a714-36948951e212.jpg)

Here is what I got from the folder:
![4381656658441_ pic](https://user-images.githubusercontent.com/39673647/176840674-90f71a55-c68d-47bf-8cb6-5c31280e4dec.jpg)

**Comment by HarryChenn** [comment]
Thank you so much for that! I am not sure if this is the desired format you will need, please let me know if there is anything wrong that I can fix.
```
import pylidc as pl
import matplotlib.pyplot as plt

patient_id = "LIDC-IDRI-0010"
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == patient_id).first()

for index in range(len(scan.annotations)): # This creates the loop that scans all nodules in one patient ID
    # Saving the mask figure first
    ann = scan.annotations[index]
    vol = ann.scan.to_volume()
    padding = [(30,10), (10,25), (0,0)]

    mask = ann.boolean_mask(pad=padding)
    fig,ax = plt.subplots(figsize=(5,3))
    ax.imshow(mask[:,:,2], cmap=plt.cm.gray)
    ax.axis('off')
    plt.tight_layout()
    fig.savefig('/Users/harrychen/Documents/LIDC-IDRI/Mask/' + str(index) + '.png', bbox_inches='tight', pad_inches=0) #This saves the mask, you can change the file location at the beginning and name it what you would like

    bbox = ann.bbox(pad=padding)
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.imshow(vol[bbox][:, :, 2], cmap=plt.cm.gray)
    ax.axis('off')
    plt.tight_layout()
    fig.savefig('/Users/harrychen/Documents/LIDC-IDRI/Slice/' + str(index) + '.png', bbox_inches='tight', pad_inches=0) #This saves the slice as well

    ann.visualize_in_3d()
    plt.tight_layout()
    plt.savefig('/Users/harrychen/Documents/LIDC-IDRI/3D/' + str(index) + '.png', bbox_inches='tight', pad_inches=0)
```
