### ISSUE TITLE
OSError: Couldn't find DICOM files for Scan(id=12,patient_id=LIDC-IDRI-0001). 

### ISSUE THREAD

**Issue by Pollob001** [notmatthancock/pylidc#54]
OSError: Couldn't find DICOM files for Scan(id=12,patient_id=LIDC-IDRI-0001).

pylidc.conf is:
[dicom]
path =C:\Users\Pollob\ct img\LIDC-IDRI
warn = True

actually where is the problem? anyone please help me.i am not able to fix****

**Comment by notmatthancock** [comment]
The error is raised here: https://github.com/notmatthancock/pylidc/blob/eb9cc8e477686c45c40d2bf982e5f27911a725c7/pylidc/Scan.py#L217-L221

which suggests that the folder `C:\Users\Pollob\ct img\LIDC-IDRI\LIDC-IDRI-0001` (the scan you are using) does not exist.

**Comment by notmatthancock** [comment]
There error is raised here, after a file search is performed:
https://github.com/notmatthancock/pylidc/blob/eb9cc8e477686c45c40d2bf982e5f27911a725c7/pylidc/Scan.py#L255-L256
I don't know why it can't find the files in your case without knowing how you're storing the dicom on your machine under the `LIDC-IDRI-0001` folder.

**Comment by Pollob001** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/74686750/179392300-99497e4f-53a7-4f9a-84ca-a2adce086895.png)

**Comment by Pollob001** [comment]
bro,can you plz check..?

**Comment by Pollob001** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/74686750/179401088-d68f3936-30f6-40cb-a9a3-4c11f969e200.png)
check this out

**Comment by notmatthancock** [comment]
The code for loading will recursively search under the folder `LIDC-IDRI-0001` until it finds a DICOM file whose series and study instance UID match the Scan object. Do you have DICOM files somewhere in the folder `LIDC-IDRI-0001`?

**Comment by rabiul-ai** [comment]
Just check your path again and again. If path is okay it will work, must.
