### ISSUE TITLE
RuntimeError: Could not establish path to dicom files in MacOS

### ISSUE THREAD

**Issue by shravaniurala** [notmatthancock/pylidc#58]
Whenever I try to visualise any of the scans, I get an error as follows :
<img width="787" alt="Screenshot 2023-01-26 at 17 40 47" src="https://user-images.githubusercontent.com/66793875/214832162-08cf6dd8-2590-4913-9ed4-172fb365073c.png">

I have made the .pylidcrc file in the required location (/Users/shravaniurala/.pylidcrc) and have also mentioned the path to my dataset in it. The dataset is in an external hard drive
<img width="520" alt="Screenshot 2023-01-26 at 17 45 35" src="https://user-images.githubusercontent.com/66793875/214832950-2d8421f5-fa4a-4e1c-8bf3-1e3a02152da5.png">

Please help me solve the same since I have tried to solve it multiple times by ensuring the file is in the correct location.

**Comment by notmatthancock** [comment]
That's triggered when `os.path.exists(...)` returns False for the path in your config file. That means either:

1. The path in your `.pylidcrc` file isn't being read correctly
2. The path `/Volumes/One Touch/Datasets/LIDC-IDRI/LIDC-IDRI` isn't correct / doesn't exist

To debug, edit the file at `~/opt/anaconda3/lib/python3.9/site-packages/pylidc/Scan.py`. Add a print statement at line 210 `print(dicompath)` to see what path is actually being tested to exist there.

**Comment by shravaniurala** [comment]
I added the `print(dicompath)` statement in `~/opt/anaconda3/lib/python3.9/site-packages/pylidc/Scan.py` and ran the code again but it isn't printing any path. How should I proceed further ?

**Comment by notmatthancock** [comment]
Did you restart your ipython kernel after making the change to ensure the updated code is imported?

**Comment by shravaniurala** [comment]
Yes I did restart the kernel. Is the issue occurring because the dataset is stored in an external drive ?

**Comment by notmatthancock** [comment]
> Is the issue occurring because the dataset is stored in an external drive ?

No. External drives work fine. There's one of two things going on right now:

1. The print statement isn't executing because it's not running the updated code; or
2. The print statement only looks like it's not doing anything because `dicompath` is blank or something.

Let's look into 2. Instead of `print(dicompath)`, let's make it more obvious, by using `print(f'The dicompath variable is: "{dicompath}"')`.

**Comment by shravaniurala** [comment]
I did that, it printed the correct path for the dataset. Along with that I deleted the previous .pylidcrc file and made a new one with the same details and that worked for me. Thanks a lot for your help !
