### ISSUE TITLE
Annotation slice number 

### ISSUE THREAD

**Issue by longchingkwok331** [notmatthancock/pylidc#65]
![image](https://github.com/notmatthancock/pylidc/assets/138690628/a5c14138-24c0-4e22-b228-d2b88790ce48)

Hi, there a GUI for visualizing the scans and some meta information by using _scan.visualize(annotation_groups=nods)_

However, is it possible to extract the information about the slice number of annotation e.g. nodule 1, near slice 25 
how can I extract this information using the pulidc functions? 

Thank you

**Comment by notmatthancock** [comment]
this example snippet might help:

```python
import numpy as np
import pylidc

scan = pylidc.query(pylidc.Scan).first()
annotation_groups = scan.cluster_annotations()

for group in annotation_groups:
    print(np.mean([annotation.contour_slice_indices.mean() for annotation in group]))

# prints: 
# 25.375
# 46.5
# 47.5
# 67.625
```

You can also use the `Annotation.centroid` and `Annotation.contours_matrix` properties.

**Comment by longchingkwok331** [comment]
thank you very much
